name: Build and Release

on:
  push:
    tags:
      - 'v*'  # v1.0, v1.1 などのタグでトリガー

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Restore .pem file from secrets
      run: |
        $pemBase64 = "${{ secrets.CHROME_EXT_PEM }}"
        $pemBytes = [System.Convert]::FromBase64String($pemBase64)
        [System.IO.File]::WriteAllBytes("dtako_chrome_ext.pem", $pemBytes)
        Write-Host ".pem file restored successfully"
      shell: powershell

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build CRX file
      run: |
        # crx3パッケージをインストール
        npm install -g crx3

        # 一時ディレクトリを作成してクリーンなファイルをコピー
        $currentDir = (Get-Location).Path
        $tempExtDir = Join-Path $env:TEMP "chrome_ext_build"

        if (Test-Path $tempExtDir) {
          Remove-Item $tempExtDir -Recurse -Force
        }
        New-Item -ItemType Directory -Path $tempExtDir | Out-Null

        # 必要なファイルのみをコピー
        $filesToCopy = @(
          "manifest.json",
          "background.js",
          "content_script.js",
          "popup.js",
          "DataDisplayConfig.js",
          "GeneralCsv.js",
          "OperationEdit.js",
          "OperationExpenseEdit.js",
          "OperationWorkEdit.js",
          "jquery-3.7.1.min.js",
          "jquery.cookie.js",
          "favicon-16x16.png",
          "favicon-32x32.png",
          "html"
        )

        foreach ($item in $filesToCopy) {
          $sourcePath = Join-Path $currentDir $item
          if (Test-Path $sourcePath) {
            Copy-Item $sourcePath -Destination $tempExtDir -Recurse -Force
            Write-Host "Copied: $item"
          }
        }

        # crx3でCRXファイルをビルド
        $pemFile = Join-Path $currentDir "dtako_chrome_ext.pem"
        $crxFile = Join-Path $currentDir "dtako_chrome_ext.crx"

        crx3 "$tempExtDir" -p "$pemFile" -o "$crxFile"

        if (Test-Path $crxFile) {
          Write-Host "CRX file created successfully"
          $fileSize = (Get-Item $crxFile).Length
          Write-Host "CRX file size: $fileSize bytes"
        } else {
          Write-Error "Failed to create CRX file"
          exit 1
        }

        # クリーンアップ
        Remove-Item $tempExtDir -Recurse -Force
      shell: powershell

    - name: Update update_manifest.xml
      run: |
        $version = "${{ github.ref_name }}".TrimStart('v')
        $content = Get-Content update_manifest.xml -Raw
        $content = $content -replace "version='[^']*'", "version='$version'"
        $content = $content -replace "download/v[^/]*/", "download/${{ github.ref_name }}/"
        Set-Content update_manifest.xml $content
        Write-Host "Updated update_manifest.xml with version $version"
      shell: powershell

    - name: Create README for ZIP
      run: |
        $readme = "# デジタコデータ取込補助 Chrome拡張機能`n`n"
        $readme += "## インストール方法`n`n"
        $readme += "1. Chromeを開いて chrome://extensions/ にアクセス`n"
        $readme += "2. 右上の「デベロッパーモード」をONにする`n"
        $readme += "3. このフォルダから「dtako_chrome_ext.crx」をChromeの拡張機能ページにドラッグ&ドロップ`n"
        $readme += "4. 「拡張機能を追加」をクリック`n`n"
        $readme += "## 使い方`n`n"
        $readme += "1. Chromeのツールバーに表示される拡張機能アイコンをクリック`n"
        $readme += "2. ID2（会社コード）、ID1、パスワードを入力して保存`n"
        $readme += "3. Ctrl+Shift+H でデジタコデータ取込ページを開く`n`n"
        $readme += "## 注意事項`n`n"
        $readme += "- 拡張機能ID: cbopaljicfjeophjpnnbgdhcpnlhobcj`n"
        $readme += "- 更新版をインストールする際も同じ手順でドラッグ&ドロップしてください`n"
        $readme += "- 拡張機能IDが同じため、自動的に更新されます`n"
        Set-Content -Path "README.txt" -Value $readme -Encoding UTF8
      shell: powershell

    - name: Create ZIP package
      run: |
        $zipFile = "dtako_chrome_ext_${{ github.ref_name }}.zip"
        Compress-Archive -Path dtako_chrome_ext.crx,README.txt -DestinationPath $zipFile
        Write-Host "Created ZIP package: $zipFile"
      shell: powershell

    - name: Create Release and Upload Asset
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dtako_chrome_ext_${{ github.ref_name }}.zip
          dtako_chrome_ext.crx
          update_manifest.xml
        name: Release ${{ github.ref_name }}
        body: |
          ## デジタコデータ取込補助 ${{ github.ref_name }}

          ### インストール方法
          1. 下記の `dtako_chrome_ext_${{ github.ref_name }}.zip` をダウンロード
          2. ZIPファイルを展開
          3. Chromeを開いて `chrome://extensions/` にアクセス
          4. 「デベロッパーモード」をONにする
          5. `dtako_chrome_ext.crx` をChromeの拡張機能ページにドラッグ&ドロップ
          6. 「拡張機能を追加」をクリック

          ### 使い方
          - Chromeツールバーの拡張機能アイコンをクリック
          - ID2（会社コード）、ID1、パスワードを入力して保存
          - Ctrl+Shift+H でデジタコデータ取込ページを開く

          ### 注意事項
          - 拡張機能ID: cbopaljicfjeophjpnnbgdhcpnlhobcj
          - 更新版も同じ手順でインストール可能（自動的に更新されます）
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
